name: Deploy site

on:
  workflow_run:
    workflows: ["Build site"]
    branches: [master]
    types: [completed]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: main.yml
          workflow_conclusion: success
          name: production-files
          path: ./production-files

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.azure_credentials }}

      - name: Upload to Azure blob storage
        uses: azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
            az account set --subscription ${{ secrets.subscription }}
            az storage blob upload-batch --account-name iwcassumptions -d '$web' -s ./production-files --overwrite true

      - name: Azure logout
        run: |
          az logout
