name: Deploy site

on:
  workflow_run:
    workflows: ["Build site"]
    branches: [master]
    types: [completed]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          workflow: main.yml
          workflow_conclusion: success

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.azure_credentials }}

      - name: Upload to Azure blob storage
        uses: azure/CLI@v1
        with:
          azcliversion: 2.0.72
          inlineScript: |
            az storage blob upload-batch --account-name iwcassumptions -d ./production-files -s '$web' 

      - name: Azure logout
        run: |
          az logout
